"""Generate LaTeX table fragments from run artifacts."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

import pandas as pd


def main(argv: Sequence[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-dir", default="runs")
    parser.add_argument("--output", default="paper/generated_tables.tex")
    args = parser.parse_args(argv)

    runs_dir = Path(args.runs_dir)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_build_tables(runs_dir), encoding="utf-8")
    print(output)


def _build_tables(runs_dir: Path) -> str:
    parts = ["% Auto-generated by scripts/generate_tables.py.\n"]
    parts.append(_overall_table(
        runs_dir / "recommended-comparison" / "metrics.csv",
        "tab:generated-standard-overall",
        "Generated standard-baseline summary.",
    ))
    parts.append(_overall_table(
        runs_dir / "modern-baselines-comparison" / "metrics.csv",
        "tab:generated-modern-overall",
        "Generated modern interpretable-baseline summary.",
    ))
    parts.append(_overall_table(
        runs_dir / "ablation-membership" / "metrics.csv",
        "tab:generated-membership-ablation",
        "Generated membership-space ablation summary.",
    ))
    return "\n".join(parts)


def _overall_table(path: Path, label: str, caption: str) -> str:
    if not path.exists():
        return f"% {label}: missing artifact {path}\n"
    df = pd.read_csv(path)
    if df.empty or "model" not in df or "balanced_accuracy_mean" not in df:
        return f"% {label}: artifact lacks expected columns in {path}\n"
    grouped = df.groupby("model", as_index=False).agg(
        balanced_accuracy=("balanced_accuracy_mean", "mean"),
        f1_macro=("f1_macro_mean", "mean"),
    ).sort_values("balanced_accuracy", ascending=False)
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Model & Balanced accuracy & Macro F1 \\",
        r"\midrule",
    ]
    for row in grouped.itertuples(index=False):
        lines.append(rf"{row.model} & {row.balanced_accuracy:.3f} & {row.f1_macro:.3f} \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    main()
