"""Generate paper tables and figures for CSRQ-Train results.

Reads evaluation results from the results/ directory and produces:
  - Table: canonical dimension vs original grammar size
  - Table: parameterization invariance summary
  - Table: learning regime balanced accuracy
  - Table: real dataset evaluation

Usage:
    uv run python scripts/generate_csrq_tables.py [--output-dir paper/tables]
"""

from __future__ import annotations

import argparse
import json
from math import comb
from pathlib import Path


def canonical_dimension(d: int, r: int) -> int:
    return sum(comb(d, l) * (2 ** l) for l in range(r + 1))


def original_grammar_size(d: int, r: int) -> int:
    return sum(comb(d, l) * (3 ** l) for l in range(r + 1))


def _format_int(n: int) -> str:
    """Format integer with LaTeX thin-space thousands separators."""
    s = f"{n:,}"
    return s.replace(",", r"\,")


def table_canonical_dimensions() -> str:
    """LaTeX table of canonical dimensions vs full grammar sizes.

    Matches the table at label tab:dimensions in paper.tex.
    """
    rows = []
    for d in [2, 5, 10, 20]:
        for r in [1, 2]:
            D = canonical_dimension(d, r)
            N = original_grammar_size(d, r)
            nullity = N - D
            rows.append(
                f"  {d} & {r} & {_format_int(D)} & {_format_int(N)} & {_format_int(nullity)} \\\\"
            )
    header = r"""\begin{table}[ht]
\centering
\caption{Canonical dimension $D_{d,r}$, full grammar size $N_{d,r}$, and expected
  semantic nullity $N_{d,r} - D_{d,r}$ for selected $(d,r)$ under strict triangular
  anchors with the product t-norm.}
\label{tab:dimensions}
\begin{tabular}{ccrrrr}
\toprule
$d$ & $r$ & $D_{d,r}$ & $N_{d,r}$ & Nullity \\
\midrule
"""
    footer = r"""\bottomrule
\end{tabular}
\end{table}
"""
    return header + "\n".join(rows) + "\n" + footer


def table_invariance_summary(results: dict | None) -> str:
    """LaTeX table for parameterization invariance results."""
    if results is None or "parameterization_stress" not in results:
        return "% No invariance results available\n"

    stress = results["parameterization_stress"].get("results", {})
    rows = []
    for name, val in stress.items():
        diff = val.get("max_canonical_diff", float("nan"))
        ok = val.get("invariant", False)
        mark = r"\checkmark" if ok else r"\times"
        rows.append(f"  {name.replace('_', ' '):20s} & {diff:.2e} & ${mark}$ \\\\")

    header = r"""
\begin{table}[ht]
\centering
\caption{Canonical coefficient invariance under dictionary reparameterization.
  Max absolute difference from base dictionary.}
\label{tab:invariance}
\begin{tabular}{lcc}
\toprule
Reparameterization & $\max|c - c_{\text{base}}|$ & Invariant ($< 10^{-6}$) \\
\midrule
"""
    footer = r"""
\bottomrule
\end{tabular}
\end{table}
"""
    return header + "\n".join(rows) + footer


def main():
    parser = argparse.ArgumentParser(description="Generate CSRQ paper tables.")
    parser.add_argument(
        "--results", default="results/csrq_evaluation.json",
        help="Path to evaluation results JSON."
    )
    parser.add_argument(
        "--output-dir", default="paper", help="Output directory for LaTeX tables."
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load results if available
    results = None
    results_path = Path(args.results)
    if results_path.exists():
        with open(results_path) as f:
            results = json.load(f)
        print(f"Loaded results from {results_path}")
    else:
        print(f"No results file found at {results_path}; generating dimension tables only.")

    dimension_table = table_canonical_dimensions()

    # Write standalone dimension table (input directly into paper.tex)
    dim_file = output_dir / "generated_dimension_table.tex"
    with open(dim_file, "w") as f:
        f.write("% Auto-generated by scripts/generate_csrq_tables.py — do not edit\n")
        f.write(dimension_table)
        f.write("\n")
    print(f"Dimension table written to {dim_file}")

    # Write combined tables file
    tables_file = output_dir / "generated_csrq_tables.tex"
    with open(tables_file, "w") as f:
        f.write("% Auto-generated CSRQ tables — do not edit manually\n")
        f.write(dimension_table)
        f.write("\n")
        f.write(table_invariance_summary(results))

    print(f"All tables written to {tables_file}")


if __name__ == "__main__":
    main()
